client_id = "d78dd3e635d5cb58866d9d38de855675"
name = "QuoteFlow"
application_url = "https://quote-flow-one.vercel.app"
embedded = true

[build]
dev_store_url = "pricing-app-3.myshopify.com"

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "write_draft_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://quote-flow-one.vercel.app/auth/callback"
]

[pos]
embedded = false
